feat: casdoor_flutter_sdk_web
casdoor/casdoor-flutter-sdk pull request #2
Opened 2022-07-07 10:56 UTC by ziliangyu

Only add casdoor_flutter_sdk_web.

2022-07-07 13:36 UTC, hsluoyz commented
@xiaobeiswift plz review

2022-07-18 17:50 UTC, hsluoyz commented
@xiaobeiswift plz review

2022-07-24 02:35 UTC, xiaobeiswift approved these changes
plz merge

2022-07-24 02:39 UTC, hsluoyz requested changes

2022-07-24 02:39 UTC, hsluoyz commented on README.md
> +| ![Android](https://cdn.jsdelivr.net/gh/ziliangyu/picb@main/screen-andriod.gif) |![iOS](https://cdn.jsdelivr.net/gh/ziliangyu/picb@main/screen-ios.gif)  |![Web](https://cdn.jsdelivr.net/gh/ziliangyu
Host these pictures inside this repo

2022-07-24 02:39 UTC, hsluoyz commented on android/src/main/kotlin/com/example/casdoor_flutter_sdk/CasdoorFlutterSdkPlugin.kt
> +package com.example.casdoor_flutter_sdk
Add Casdoor license headers to all source code files

2022-07-24 03:47 UTC, hsluoyz approved these changes

2022-07-24 03:50 UTC, merged

2022-08-07 08:12 UTC, hsluoyz commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/casdoor/casdoor-flutter-sdk/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: